version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DEBUG: "True"
      DB_NAME: ecom
      DB_USER: tommi
      DB_PASSWORD: 209325
      DB_HOST: db  # Corrected from localhost to service name `db`
      DB_PORT: 3306
      SECRET_KEY: "SECRET_KEY"
      ALLOWED_HOSTS: "localhost,127.0.0.1"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ecom  # Corrected to match the DB_NAME environment variable
      MYSQL_USER: tommi  # Corrected to match DB_USER
      MYSQL_PASSWORD: 209325  # Corrected to match DB_PASSWORD
    ports:
      - "3307:3306"  # Expose the port 3307 on the host, but inside the container it’s 3306
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
